### ISSUE TITLE
fail to compile

### ISSUE THREAD

**Issue by madeinmario** [KikiHobbyRepair/SpaceRat#4]
'Mouse' not found. Does your sketch include the line '#include <Mouse.h>'?
![image](https://user-images.githubusercontent.com/67102369/152762427-e5901dba-90c3-4042-8551-f39fff32af31.png)-ide version 1.8.57 windows store

**Comment by madsi1m** [comment]
you need to install the mouse lib in your arduino ide

**Comment by KikiHobbyRepair** [comment]
As @madsi1m told make sure to install the latest version of the libraries (Mouse.h, Keyboard.h etc)

**Comment by madeinmario** [comment]
is not the library, i got it compiled with the online arduine ide and visual studio code, but with arduino ide i get that error , i did chek the livrary folder and it’s installed

Made in Mario 2021
;)
