### ISSUE TITLE
What kind of spring did you use?

### ISSUE THREAD

**Issue by 10bn** [KikiHobbyRepair/SpaceRat#6]
What kind of spring did you use?

**Comment by S0und** [comment]
He have mentioned in his first video: https://youtu.be/7DKmMXRq_Xc?t=221

It's a 3D printer bed spring, super popular with Ender3 printers. "3d printer bed spring" just search for this on Aliexpress.

**Comment by KikiHobbyRepair** [comment]
As S0ound wrote above look for 3D printer spring. Take care of the dimensions.
